// Settings
#define kUsername @"Username"
#define kPassword @"Password"
#define kServerAddress @"ServerAddress"

// URLs
#define kURLLogin @"/api/login/"
#define kURLLogout @"/api/logout/"
#define kURLGuests @"/api/guests/"
#define kURLNames @"/api/names/"
#define kURLCheckin @"/api/checkin/"

// Table keys
#define kUninitialized @"..."
#define kA @"A"
#define kB @"B"
#define kC @"C"
#define kD @"D"
#define kE @"E"
#define kF @"F"
#define kG @"G"
#define kH @"H"
#define kI @"I"
#define kJ @"J"
#define kK @"K"
#define kL @"L"
#define kM @"M"
#define kN @"N"
#define kO @"O"
#define kP @"P"
#define kQ @"Q"
#define kR @"R"
#define kS @"S"
#define kT @"T"
#define kU @"U"
#define kV @"V"
#define kW @"W"
#define kX @"X"
#define kY @"Y"
#define kZ @"Z"

